### ISSUE TITLE
deployment scripts are redundant

### ISSUE THREAD

**Issue by gureckis** [NYUCCL/smile#1]
in violation of DRY (don't repeat yourself), `.github/workflows/deploy-hash.yml` and `.github/workflows/deploy.yml` are more of less copies of each other.  

future updates to either script will require making coordinated changes in both places.  

a better approach would be to abstract things into a reusable workflow: https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by gureckis** [comment]
@guydav I just went ahead and solved this in an easy way via chat gpt

**Comment by guydav** [comment]
I, for one, welcome our new machine overlords.
