### ISSUE TITLE
query strings appear twice in URLS and it starts causing problems sometimes

### ISSUE THREAD

**Issue by gureckis** [NYUCCL/smile#133]
The landing page for prolific users is:

http://localhost:3010/nyuccl/smile/?PROLIFIC_PID=XXXX&STUDY_ID=XXXX&SESSION_ID=XXXXX#/welcome/prolific/

as we have figured out in older issue (#82) vuerouter believes that commands that come before the `#` are not in bounds for the router.  to catch this we added code which grabs the query strings that come before the `#` and adds them to the end.  the results is the URL becomes

http://localhost:3010/nyuccl/smile/?PROLIFIC_PID=XXXX&STUDY_ID=XXXX&SESSION_ID=XXXXX#/consent?PROLIFIC_PID=XXXX&STUDY_ID=XXXX&SESSION_ID=XXXXX

for the consent page (and so on).  the problem is just that it looks weird and makes problems later.  for example, if you click Random Fake Prolific User, and then use the dev tools to go back to the / recruit page then click Random Fake CloudResearch User then your URL carries forward the PROLIFIC information when you go to CloudResearch welcome screen.

http://localhost:3010/nyuccl/smile/trial_component_api/?PROLIFIC_PID=XXXX&STUDY_ID=XXXX&SESSION_ID=XXXXX#/welcome/cloudresearch/?assignmentId=123RVWYBAZW00EXAMPLE456RVWYBAZW00EXAMPLE&hitId=123RVWYBAZW00EXAMPLE&turkSubmitTo=https://www.mturk.com/&workerId=AZ3456EXAMPLE

Honestly I think the prolific landing page might need to be a lightweight redirect HTML page that is served up and immediately reformats and redirects to the full app.  so like need a prolific.html in addition to index.html that is empty but immediately reformats the query strings and passes into the app.

(*) I complained to prolific about this again, not sure if they do anything.

**Comment by emilyliquin** [comment]
I also ran one study where a lot of the prolific ids were missing for some reason, apparently didn't get saved. Not sure if this was because of the URL issues or something else.

**Comment by gureckis** [comment]
I think chat GPT helped me close this.  before the main page loads it checks to see if this pathological case of query string appearing between # routes and flips it.  it runs so fast it doesn't incur much of a performance cost despite requiring the page to reload.  it is smart enough that it does nothing if websites provide the query strings in the correct place (like every site except prolific)
