### ISSUE TITLE
status code on prolific doesn't let us see easily if person didn't finish task, etc...  

### ISSUE THREAD

**Issue by gureckis** [NYUCCL/smile#75]
maybe add a human readable code to completion code so we can tell more easily if subject is entitled to full compensation, etc...

**Comment by rhezab** [comment]
this is what i did, but also i never successfully used the completion code to check the data or whatever

**Comment by gureckis** [comment]
@Le-Gris since you were playing with this part of the code, perhaps you have some idea about this.  the idea is that in addition to the hashed code it might be nice to be able just to look at the final code an known if the subject completed or withdrew or whatever.  so it would mean like adding some known characters to the end of the completion code that we know how to interpret.  could be useful for automating payment processing.
