### ISSUE TITLE
Refreshing page not in dev mode doesn't work

### ISSUE THREAD

**Issue by rhezab** [NYUCCL/smile#80]
see linked code snippet - https://github.com/NYUCCL/smile/blob/ba3239653faca5d5fc9e17cfcb05adace01cf7d8/src/router.js#L227C1-L237C6

These if statement should swap order... I've checked that this fixes the bug.

The second if statement (lines 234-237) handles refreshing, but the first statement throws an error when page is refreshed because `from.meta.next` is undefined.

So should check for refresh first. Should probably check for everything else first too before handling the randomized subtimeline case. But I'm not using randomized subtimeline, so maybe that changes things if you are...

**Comment by gureckis** [comment]
@guydav isn't this the same thing you fixed?

**Comment by gureckis** [comment]
@rhezab can you please verify this is working based on @guydav commit and if so close the issue?  thanks.
