### ISSUE TITLE
URL params before # isn't processed correctly

### ISSUE THREAD

**Issue by rhezab** [NYUCCL/smile#82]
in addGuards beforeEach in `router.js`, if you `console.log(to.query)`, it is empty even though it should contain the URL params.

It can be manually read like this (courtesy of Emily), and `queryDict` can be used instead of `to.query` as an argument to `processQuery`:

```
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const queryDict = {}
    for (const [key, value] of urlParams.entries()) {
        queryDict[key] = value
    }
```

Since the problem happens in beforeEach (the first time `to.query` is touched), the bug may be in vue-js/router instead of in smile.

**Comment by rhezab** [comment]
For example, 

```
// welcome screen for referral
timeline.pushSeqRoute({
  path: '/welcome/:service',
  name: 'welcome_referred',
  component: Advertisement,
  meta: { next: 'consent', allowDirectEntry: true }, // override what is next
  beforeEnter: (to) => {
    // processQuery(to.query, to.params.service)
    // console.log('to query ', to)
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const queryDict = {}
    for (const [key, value] of urlParams.entries()) {
        queryDict[key] = value
    }
    processQuery(queryDict, to.params.service)
  },
})
```

**Comment by gureckis** [comment]
This is fine to leave here for documentation but if this is correct it should be raise with vuerouter package as an issue or discussion on that repo's list.

**Comment by rhezab** [comment]
also auto refer to the prolific welcome page

```
// auto refer to the anonymous welcome page
timeline.pushRoute({
    path: '/',
    name: 'landing',
    redirect: {name: 'welcome_referred', params: {service: 'prolific'}},
    meta: { allowDirectEntry: true },
})
```

**Comment by gureckis** [comment]
@rhezab  what does "also" mean in this context?

**Comment by gureckis** [comment]
I opened a issue in the vuerouter project page to address this: https://github.com/vuejs/router/issues/2054

**Comment by gureckis** [comment]
see above but a member of the core Vuejs team says that this behavior is expected of the vuerouter.  as a result smile is going to need to implement a solution for this.  my suggestion would be to add something to beforeEach/beforeEnter in smile which processes all the query parameters in the URL and collects them up so that we can process them.  should be default behavior, not implemented on a per-route basis.

**Comment by gureckis** [comment]
implemented.
