### ISSUE TITLE
rm node-sass from package.json

### ISSUE THREAD

**Issue by rhezab** [NYUCCL/smile#83]
it raises problems when you try to `npm install` it

**Comment by rhezab** [comment]
turns out this is needed for `css-build` script in `package.json`, which is called in `deploy.yml`. 

perhaps can replace with sass CLI?? https://bulma.io/documentation/customize/with-sass-cli/

**Comment by gureckis** [comment]
weird because github actions builds a custom node environment each time it deploys and so it successfully installs this.  perhaps the version of node you are running locally is out of sync with what smile currently expects?

**Comment by gureckis** [comment]
i'm running
➜ node --version
v20.3.0
